const data=[['Street studies','街拍','Paris, in passing','0','Barbare Kacharava','https://unsplash.com/photos/UeAqjB9Py84'],['In monochrome','黑白','Light, stripped bare','1','Annie Spratt','https://unsplash.com/photos/90CTYAUzLJQ'],['People, quietly','人像','The spaces between words','2','Mykyta Kravčenko','https://unsplash.com/photos/oI3LIUxpdwM'],['Elsewhere','风景','A little further from here','3','Barbare Kacharava','https://unsplash.com/photos/BPHyN1U_ci8'],['Small things','静物','An ordinary kind of beauty','4','Roger Bradshaw','https://unsplash.com/photos/jzlevTsf1kE'],['Passing moments','日常','Nothing happening. Everything happening.','5','Richard Stachmann','https://unsplash.com/photos/oyw1I1F_sYo']];
const gallery=document.querySelector('#gallery');const categories=document.querySelector('#heroCategories');
const workTypes=[{name:'Photography',hash:'photography',image:'0',alt:'Paris, in passing'},{name:'Film',hash:'film',image:'5',alt:'Passing time'},{name:'Studio Art',hash:'studio-art',image:'4',alt:'Studies in form'}];let currentHero=0,heroTimer;
function showHero(i){if(i===currentHero)return;clearTimeout(heroTimer);currentHero=i;const front=document.querySelector('#heroImage'),next=document.querySelector('#heroNext');next.src=`images/${workTypes[i].image}.jpg`;next.classList.add('active');front.classList.remove('active');heroTimer=setTimeout(()=>{front.src=next.src;front.alt=workTypes[i].alt;front.classList.add('active');next.classList.remove('active')},650);document.querySelectorAll('.hero-category').forEach((a,n)=>a.classList.toggle('selected',i===n))}
workTypes.forEach((type,i)=>{const a=document.createElement('a');a.href=`#${type.hash}`;a.className='hero-category'+(i===0?' selected':'');a.textContent=type.name;a.addEventListener('pointerenter',()=>showHero(i));a.addEventListener('focus',()=>showHero(i));categories.append(a)});
data.forEach((d,i)=>{const article=document.createElement('article');article.className='archive-row';article.innerHTML=`<a class="archive-photo" href="#series-${i+1}" aria-label="Open ${d[0]} / ${d[1]}"><img src="images/${d[3]}.jpg" alt="${d[2]}" loading="lazy"></a><div class="archive-copy"><span class="category-label">${d[1]} / PHOTOGRAPHY</span><h3><a href="#series-${i+1}">${d[0]}</a></h3><p>${d[2].replace(/\.$/,'')}.</p><a class="series-link" href="#series-${i+1}">VIEW SERIES</a><span class="row-number">0${i+1} / 2026</span></div>`;gallery.append(article)});
const menu=document.querySelector('#siteMenu'),menuToggle=document.querySelector('#menuToggle'),backdrop=document.querySelector('#menuBackdrop');
function closeMenu(){const wasOpen=!menu.hidden;menu.hidden=true;backdrop.hidden=true;menuToggle.setAttribute('aria-expanded','false');document.body.classList.remove('menu-open');if(wasOpen)menuToggle.focus({preventScroll:true})}
menuToggle.onclick=()=>{if(!menu.hidden){closeMenu();return}menu.hidden=false;backdrop.hidden=false;menuToggle.setAttribute('aria-expanded','true');document.body.classList.add('menu-open');document.querySelector('#closeMenu').focus({preventScroll:true})};document.querySelector('#closeMenu').onclick=closeMenu;backdrop.onclick=closeMenu;menu.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu();if(e.key==='Tab'&&!menu.hidden){const targets=[...menu.querySelectorAll('button,a')],first=targets[0],last=targets.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});document.querySelector('#scrollWorks').onclick=()=>document.querySelector('#works').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});
const lightbox=document.querySelector('#lightbox');let activeSeries=[],activePhoto=0;
function renderPhoto(){const photo=activeSeries[activePhoto];document.querySelector('#fullImage').src=photo.src;document.querySelector('#fullImage').alt=photo.title;document.querySelector('#fullImage').classList.toggle('monochrome',photo.monochrome);document.querySelector('#fullCaption').textContent=photo.title;document.querySelector('#photoCounter').textContent=`${activePhoto+1} / ${activeSeries.length}`;const following=new Image();following.src=activeSeries[(activePhoto+1)%activeSeries.length].src}
function openPhoto(photos,index){activeSeries=photos;activePhoto=index;renderPhoto();lightbox.showModal();document.body.classList.add('viewer-open')}
function stepPhoto(direction){activePhoto=(activePhoto+direction+activeSeries.length)%activeSeries.length;renderPhoto()}
document.querySelector('#closeLightbox').onclick=()=>lightbox.close();document.querySelector('#previousPhoto').onclick=()=>stepPhoto(-1);document.querySelector('#nextPhoto').onclick=()=>stepPhoto(1);lightbox.addEventListener('close',()=>document.body.classList.remove('viewer-open'));lightbox.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();stepPhoto(e.key==='ArrowLeft'?-1:1)}});let touchStart=null;lightbox.addEventListener('touchstart',e=>{touchStart=e.touches.length===1?{x:e.touches[0].clientX,y:e.touches[0].clientY}:null},{passive:true});lightbox.addEventListener('touchend',e=>{if(touchStart){const dx=e.changedTouches[0].clientX-touchStart.x,dy=e.changedTouches[0].clientY-touchStart.y;if(Math.abs(dx)>60&&Math.abs(dx)>Math.abs(dy)*1.3)stepPhoto(dx>0?-1:1)}touchStart=null},{passive:true});lightbox.addEventListener('touchcancel',()=>{touchStart=null},{passive:true});
document.querySelector('#back').onclick=document.querySelector('#aboutBack').onclick=()=>location.hash='';
function route(){closeMenu();const hash=location.hash;const match=hash.match(/^#series-([1-6])$/);const about=hash==='#about';document.body.classList.toggle('detail-page',!!match||about);document.querySelector('#index').hidden=!!match||about;document.querySelector('#collection').hidden=!match;document.querySelector('#about').hidden=!about;document.querySelector('#homeLink').toggleAttribute('aria-current',!about);document.querySelector('#aboutLink').toggleAttribute('aria-current',about);if(match){const i=Number(match[1])-1,d=data[i];document.querySelector('#collectionNumber').textContent=`SERIES 0${i+1} / ${d[1]}`;document.querySelector('#collectionTitle').textContent=d[0];document.querySelector('#collectionSub').textContent=d[2].replace(/\.$/,'')+'.';const series=document.querySelector('#series');series.innerHTML='';const photos=[{src:`images/${d[3]}.jpg`,title:`${d[2].replace(/\.$/,'')}, 2026`,monochrome:i===1},...(window.seriesAssets[i]||[]).map((src,n)=>({src,title:`${d[0]} — Study ${String(n+2).padStart(2,'0')}, 2026`,monochrome:i===1}))];photos.forEach((photo,n)=>{const button=document.createElement('button');button.className='series-photo';button.setAttribute('aria-label',`Open photograph ${n+1}: ${photo.title}`);button.innerHTML=`<img src="${photo.src}" alt="${photo.title}" loading="lazy" class="${photo.monochrome?'monochrome':''}">`;button.onclick=()=>openPhoto(photos,n);series.append(button)});const credit=document.createElement('p');credit.className='series-credit';credit.innerHTML=`Opening photograph: <a href="${d[5]}" target="_blank" rel="noopener">${d[4]}</a>. Additional demo selections: <a href="https://unsplash.com" target="_blank" rel="noopener">Unsplash</a>.`;series.append(credit)}const sectionId=['catalog','photography','film','studio-art'].find(id=>hash==='#'+id);if(sectionId){requestAnimationFrame(()=>document.querySelector('#'+sectionId).scrollIntoView({behavior:'instant'}))}else{window.scrollTo({top:0,behavior:'instant'})}}window.addEventListener('hashchange',route);route();
const hero=document.querySelector('.hero');const observer=new IntersectionObserver(([entry])=>document.body.classList.toggle('past-hero',!entry.isIntersecting),{threshold:0,rootMargin:'-90px 0px 0px 0px'});observer.observe(hero);

function updateHeader(){document.body.classList.toggle("past-hero",window.scrollY>=hero.offsetHeight-100)}window.addEventListener("scroll",updateHeader,{passive:true});updateHeader();
