const data=[['Color','Photography','Photography','a-movable-feast','Jade Li',''],['Monochrome','Photography','Photography','ashes-of-time','Jade Li',''],['Analog','Photography','Photography','warm-ghost-1','Jade Li','']];
const gallery=document.querySelector('#gallery');const categories=document.querySelector('#heroCategories');
const workTypes=[{name:'Photography',hash:'photography',image:'waves',alt:'Waves — Jade Li'},{name:'Film',hash:'film',image:'film-coming-soon',alt:'Film Coming Soon — Jade Li'}];let currentHero=0,heroTimer;
function showHero(i){currentHero=i;document.querySelectorAll('.hero-category').forEach((a,n)=>a.classList.toggle('selected',i===n))}
workTypes.forEach((type,i)=>{const a=document.createElement('a');a.href=`#${type.hash}`;a.className='hero-category'+(i===0?' selected':'');a.textContent=type.name;a.addEventListener('pointerenter',()=>showHero(i));a.addEventListener('focus',()=>showHero(i));categories.append(a)});
data.forEach((d,i)=>{const article=document.createElement('article');article.className='archive-row';article.innerHTML=`<a class="archive-photo" href="#series-${i+1}" aria-label="Open ${d[0]} / ${d[1]}"><img src="images/${d[3]}.jpg" alt="${d[2]}" loading="lazy"></a><div class="archive-copy"><span class="category-label">${d[1]} / PHOTOGRAPHY</span><h3><a href="#series-${i+1}">${d[0]}</a></h3><p>${i<3?'&nbsp;':i===3?'Coming soon':d[2].replace(/\.$/,'')+'.'}</p><a class="series-link" href="#series-${i+1}">VIEW SERIES</a><span class="row-number">0${i+1} / 2026</span></div>`;gallery.append(article)});
const menu=document.querySelector('#siteMenu'),menuToggle=document.querySelector('#menuToggle'),backdrop=document.querySelector('#menuBackdrop');
function closeMenu(){const wasOpen=!menu.hidden;menu.hidden=true;backdrop.hidden=true;menuToggle.setAttribute('aria-expanded','false');document.body.classList.remove('menu-open');if(wasOpen)menuToggle.focus({preventScroll:true})}
menuToggle.onclick=()=>{if(!menu.hidden){closeMenu();return}menu.hidden=false;backdrop.hidden=false;menuToggle.setAttribute('aria-expanded','true');document.body.classList.add('menu-open');document.querySelector('#closeMenu').focus({preventScroll:true})};document.querySelector('#closeMenu').onclick=closeMenu;backdrop.onclick=closeMenu;menu.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu();if(e.key==='Tab'&&!menu.hidden){const targets=[...menu.querySelectorAll('button,a')],first=targets[0],last=targets.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
const lightbox=document.querySelector('#lightbox');let activeSeries=[],activePhoto=0;
function renderPhoto(){const photo=activeSeries[activePhoto];document.querySelector('#fullImage').src=photo.src;document.querySelector('#fullImage').alt=photo.title;document.querySelector('#fullImage').classList.toggle('monochrome',photo.monochrome);document.querySelector('#fullCaption').textContent=photo.title;document.querySelector('#photoCounter').textContent=`${activePhoto+1} / ${activeSeries.length}`;const following=new Image();following.src=activeSeries[(activePhoto+1)%activeSeries.length].src}
function openPhoto(photos,index){activeSeries=photos;activePhoto=index;renderPhoto();lightbox.showModal();document.body.classList.add('viewer-open')}
function stepPhoto(direction){activePhoto=(activePhoto+direction+activeSeries.length)%activeSeries.length;renderPhoto()}
document.querySelector('#closeLightbox').onclick=()=>lightbox.close();document.querySelector('#previousPhoto').onclick=()=>stepPhoto(-1);document.querySelector('#nextPhoto').onclick=()=>stepPhoto(1);lightbox.addEventListener('close',()=>document.body.classList.remove('viewer-open'));lightbox.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();stepPhoto(e.key==='ArrowLeft'?-1:1)}});let touchStart=null;lightbox.addEventListener('touchstart',e=>{touchStart=e.touches.length===1?{x:e.touches[0].clientX,y:e.touches[0].clientY}:null},{passive:true});lightbox.addEventListener('touchend',e=>{if(touchStart){const dx=e.changedTouches[0].clientX-touchStart.x,dy=e.changedTouches[0].clientY-touchStart.y;if(Math.abs(dx)>60&&Math.abs(dx)>Math.abs(dy)*1.3)stepPhoto(dx>0?-1:1)}touchStart=null},{passive:true});lightbox.addEventListener('touchcancel',()=>{touchStart=null},{passive:true});
document.querySelector('#back').onclick=document.querySelector('#aboutBack').onclick=()=>location.hash='';
function route(){closeMenu();const hash=location.hash;const match=hash.match(/^#series-([1-3])$/);const studio=false;const about=hash==='#about';document.body.classList.toggle('detail-page',!!match||studio||about);document.querySelector('#index').hidden=!!match||studio||about;document.querySelector('#collection').hidden=!match&&!studio;document.querySelector('#about').hidden=!about;document.querySelector('#homeLink').toggleAttribute('aria-current',!about);document.querySelector('#aboutLink').toggleAttribute('aria-current',about);if(match||studio){const i=studio?4:Number(match[1])-1,d=studio?['Studio Art','Studio Art','Coming soon','night-balcony','Jade Li','']:data[i];document.querySelector('#collectionNumber').textContent='';document.querySelector('#collectionTitle').textContent=d[0];document.querySelector('#collectionSub').textContent=studio||i<3?'\u00a0':i===3?'Coming soon':d[2].replace(/\.$/,'')+'.';const series=document.querySelector('#series');series.innerHTML='';const photos=studio?window.studioArtPhotos:window.customSeries[i];photos.forEach((photo,n)=>{const button=document.createElement('button');button.className='series-photo';button.setAttribute('aria-label',`Open photograph ${n+1}: ${photo.title}`);button.innerHTML=`<img src="${photo.src}" alt="${photo.title}" loading="lazy" class="${photo.monochrome?'monochrome':''}">`;button.onclick=()=>openPhoto(photos,n);series.append(button)});}const sectionId=['catalog','photography','film'].find(id=>hash==='#'+id);if(sectionId){requestAnimationFrame(()=>document.querySelector('#'+sectionId).scrollIntoView({behavior:'instant'}))}else{window.scrollTo({top:0,behavior:'instant'})}}window.addEventListener('hashchange',route);route();
const hero=document.querySelector('.hero');const observer=new IntersectionObserver(([entry])=>document.body.classList.toggle('past-hero',!entry.isIntersecting),{threshold:0,rootMargin:'-90px 0px 0px 0px'});observer.observe(hero);

function updateHeader(){document.body.classList.toggle("past-hero",window.scrollY>=hero.offsetHeight-100)}window.addEventListener("scroll",updateHeader,{passive:true});updateHeader();
